version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:8080"


  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://localhost:5000