# Stage 1: Build the Angular app
FROM node:latest as build-client
WORKDIR /app
COPY azcoreweb.client/package*.json ./
RUN npm install
COPY azcoreweb.client ./
RUN npm run build

# Stage 2: Serve the Angular app
FROM nginx:alpine
COPY --from=build-client /app/dist/azcoreweb.client/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]